### PR TITLE
feat(flake): create a new flake

### PR DESCRIPTION
**Pull request by amadalusia**
### What does this do?
It gives NixOS users the chance to try this tool, without having to make a package for it on their own, which is great!

### Why?
I got bored and started looking through a programming channel in a discord server I am in and I found someone talking about this. So I just made a flake for it instead of learning a programming language.

You also get other users using Nix to try before they buy, or install it if they so want to.

Thanks for this neat package and have a good day!

### CODE REVIEW

**Comment by vainangel** [comment]
Hi @amadalusia, thanks for the feature suggestion.

Although I don't know anything about NixOS and Flakes (I assume the OS's package management suite?), I do notice that your package.nix does not call upon the Makefile written at the root of the repo, which handles program compilation and installation. This can cause issues with with synchronization in the future, in the event that the Makefile is updated. Would it be possible to call `make` instead of invoking GCC directly? This has the added benefit of allowing the end-user (Flake user) to override the Makefile args if necessary, and also allows them to debug issues through the Makefile directly.

Also, I noticed you specified a `0.1.0` version at the top of package.nix. It hadn't occurred to me to attach versioning metadata to the package, since it was initially a simple C program. Once changes are made to the Flake to use `make`, I will accept the PR and also add my own updates to include this versioning in the rest of the repo.

Lastly, since the installation varies between NixOS and other Linux distributions, could you include a section in `Installation` for NixOS Flakes?

Thank you!

**Comment by amadalusia** [comment]
Hey, thanks for checking my PR!

For the differing installations, I will include that in the README later, thanks for the reminder!

For the Makefile, I originally had it not successful because of hardcoded paths which means the Makefile will need to be changed in order to accommodate not calling make, I have tried about doing that without much success but I can try my hand at it again.

For versions, I know there exists a function in nixpkgs lib which grabs the commit hash and uses that for the version but I don't remember the name of it.

I'll check these out when I find the time to do so. Cheers!

**Comment by vainangel** [comment]
Hi @amadalusia,

The version info can remain hard-coded for now. It isn't a concern since it won't really break portability. I'll keep it as 0.1.0 and make note to update the Flake when I update the versioning, though I hardly have reason too.

Focus primarily on the Flake configuration, such that `make` can be called to build the program. Installation is up to you, since, as far as I understand, installation on NixOS is different from other Linux systems. I'm mainly concerned with `make` for the puppyfetch target working as intended, I don't care for the `make install`/`uninstall` phony targets, since they're domain-specific anyways.

Thanks!

**Comment by amadalusia** [comment]
ROFL, just realised I could just not set buildPhase, I'll fix that in the next commit.

I can focus on docs, theres a few ways you could go about installing or running packages on Nix(OS), After you can either make a tagged release or I can find out what function I need.

Cheers again!

**Comment by vainangel** [comment]
Hi @amadalusia,

I see. Thanks for looking into it <3 I'll accept the PR when the docs and `make` patches are made. Thank you again! :3

**Comment by amadalusia** [comment]
thanks midi (this was actually my bad because i forgot to change the git username and useremail)

**Comment by vainangel** [comment]
Accepted. thanks <3

**Pull request merged**
